# Generated by Django 6.0.4 on 2026-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('tasks', models.ManyToManyField(blank=True, to='task.taskmodel')),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
            },
        ),
    ]
